<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="PyBroTheme.xshd" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="PyBroTheme.xshd">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AvalonEdit" Version="6.3.1.120" />
		<PackageReference Include="MahApps.Metro.IconPacks.Material" Version="6.2.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Commands\PyBro.Commands.csproj" />
		<ProjectReference Include="..\PyBro.Contracts\PyBro.Contracts.csproj" />
	</ItemGroup>

</Project>